### ISSUE TITLE
License

### ISSUE THREAD

**Issue by siolag161** [PlusHaze/TrayNotification#6]
Hello,

First thanks for the nice work. I would like to ask you what the license is. Are there any restrictions for commercial/closed-source use?

Thanks

**Comment by PlusHaze** [comment]
Before I add a license, I looked at my options and I was slightly confused. Could you help me pick one that's best? From http://choosealicense.com/, I figured the two licenses I would need is
http://prnt.sc/aad30b
but not sure which one to pick.

What I care about is: I want something people can freely contribute into, improve, use, share, so long as they credit me as being the original author and NOT try to sell the software then I'm not bothered.

**Comment by siolag161** [comment]
Hi, thanks for your reply. IMHO, I think you should go with MIT for a project like this. Apache is like they say, if you think about patents & stuffs.

**Comment by PlusHaze** [comment]
Thanks. Done.

**Comment by N-hakk** [comment]
Hello Sialog161,
I read your Lengow project code and I have questions? if possible of course
You can contact me hakkari.nawfal@gmail.com
