### ISSUE TITLE
ExceptionInInitializerError

### ISSUE THREAD

**Issue by xahon** [PlusHaze/TrayNotification#8]
This my code (From your wiki)

```
public static void main(String[] args) {
        String title = "Congratulations sir";
        String message = "You've successfully created your first Tray Notification";
        NotificationType notification = NotificationType.SUCCESS;

        TrayNotification tray = new TrayNotification();
        tray.setTitle(title);
        tray.setMessage(message);
        tray.setNotificationType(notification);
        tray.showAndWait();
    }
```

It terminates with:

>   Exception in thread "main" java.lang.ExceptionInInitializerError
>   at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
>   at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
>   at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
>   at java.lang.reflect.Constructor.newInstance(Unknown Source)
>   at java.lang.Class.newInstance(Unknown Source)
>   at sun.reflect.misc.ReflectUtil.newInstance(Unknown Source)
>   at javafx.fxml.FXMLLoader$InstanceDeclarationElement.constructValue(FXMLLoader.java:1009)
>   at javafx.fxml.FXMLLoader$ValueElement.processStartElement(FXMLLoader.java:746)
>   at javafx.fxml.FXMLLoader.processStartElement(FXMLLoader.java:2707)
>   at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2527)
>   at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2441)
>   at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2409)
>   at tray.notification.TrayNotification.initTrayNotification(TrayNotification.java:77)
>   at tray.notification.TrayNotification.<init>(TrayNotification.java:68)
>   at Main.main(Main.java:25)
> Caused by: java.lang.IllegalStateException: Toolkit not initialized
>   at com.sun.javafx.application.PlatformImpl.runLater(PlatformImpl.java:273)
>   at com.sun.javafx.application.PlatformImpl.runLater(PlatformImpl.java:268)
>   at com.sun.javafx.application.PlatformImpl.setPlatformUserAgentStylesheet(PlatformImpl.java:550)
>   at com.sun.javafx.application.PlatformImpl.setDefaultPlatformUserAgentStylesheet(PlatformImpl.java:512)
>   at javafx.scene.control.Control.<clinit>(Control.java:87)
>   ... 15 more

**Comment by PlusHaze** [comment]
That's because the program is not being run on a JavaFX thread. You're currently using the default for Java. Create a new JavaFX application and run the code again and it will work.

**Comment by noutijo** [comment]
Thanks you very much  ...
